name: Keep Render API Awake

on:
　workflow_dispatch:
  schedule:
    # 毎日 8:00〜15:30 の間、15分おき（UTC時間を使う）
    - cron: '0 23 * * 1-5'
    - cron: '15 23 * * 1-5'
    - cron: '30 23 * * 1-5'
    - cron: '45 23 * * 1-5'
    - cron: '0 0 * * 1-5'
    - cron: '15 0 * * 1-5'
    - cron: '30 0 * * 1-5'
    - cron: '45 0 * * 1-5'
    - cron: '0 1 * * 1-5'
    - cron: '15 1 * * 1-5'
    - cron: '30 1 * * 1-5'
    - cron: '45 1 * * 1-5'
    - cron: '0 2 * * 1-5'
    - cron: '15 2 * * 1-5'
    - cron: '30 2 * * 1-5'
    - cron: '45 2 * * 1-5'

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl the Render API
        run: |
          curl -s https://stock-api-wz9e.onrender.com/stock?symbol=7203.T
